In [14]:
import numpy as np
my_list = [1,2,3,4]
arr1 = np.array(my_list)
arr1, my_list

(array([1, 2, 3, 4]), [1, 2, 3, 4])

In [8]:
arr1 * 10 # element wise or Broadcast

array([10, 20, 30, 40])

In [16]:
my_list2 = [
    [1,2,3],
    [4,5,6],
]
my_list2[1]

[4, 5, 6]

In [19]:
arr2 = np.array(my_list2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr2[:,1] # [행번호, 열번호] ':'은  전체를 의미

array([2, 5])

In [23]:
arr2[:,[0,2]] # 팬시 인덱싱(띄엄띄엄 추출)

array([[1, 3],
       [4, 6]])

## arr3 (2,2,3) 2면 2행 3열

In [30]:
arr3 = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [1,2,3],
            [4,5,6]
        ]
    ]
)
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [26]:
np.array([[[0,1,2,3],
          [4,5,6,7],
          [8,9,10,11]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [36]:
np.arange(0,3,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [46]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [50]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [56]:
np.full((3,4),-1)

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [62]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [55]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [63]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

In [69]:
arr2.shape,arr2.size

((2, 3), 6)

In [80]:
np.array([1.,2.,'3']) # 표현방식이 좀 더 많은 쪽을 따라감

array(['1.0', '2.0', '3'], dtype='<U32')

In [81]:
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [83]:
arr2, arr2.T

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [96]:
arr4 = np.arange(16)
arr4.reshape(2,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [92]:
arr4.reshape(4,4), arr4.reshape(4,4).shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 (4, 4))

In [94]:
arr4.reshape(-1,8), arr4.reshape(-1,8).shape # -1 분할시 알아서 계산

(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 (2, 8))

In [98]:
arr2.astype(np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [99]:
arr2.dtype

dtype('int32')

In [131]:
# 아파트 실거래데이터 읽기
import pandas as pd
apt_price = pd.read_csv(
    "./apt_price_2022.csv",
    encoding='cp949',
    skiprows=15,
    thousands=','
)
apt_price

시군구      번지     본번    부번             단지명  전용면적(㎡)    계약년월  \
0      서울특별시 강남구 개포동   658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202109   
1      서울특별시 강남구 개포동   658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202112   
2      서울특별시 강남구 개포동   658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
3      서울특별시 강남구 개포동   658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
4      서울특별시 강남구 개포동   658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202205   
...              ...     ...    ...   ...             ...      ...     ...   
16942  서울특별시 중랑구 중화동     450  450.0   0.0  한신아파트(103~109)    59.76  202207   
16943  서울특별시 중랑구 중화동     450  450.0   0.0  한신아파트(103~109)    84.03  202207   
16944  서울특별시 중랑구 중화동  274-51  274.0  51.0         한영(101)    84.69  202111   
16945  서울특별시 중랑구 중화동  274-51  274.0  51.0         한영(101)    84.69  202204   
16946  서울특별시 중랑구 중화동    11-7   11.0   7.0     현대휴앤미(102동)    76.43  202204   

       계약일  거래금액(만원)   층    건축년도          도로명  해제사유발생일  거래유형          중개사소재지  
0        2    220000   2  1987.0        언주로 3      NaN     -               -  
1        4    215000   3  1987.0        언주로 3      NaN  중개거래          서울 강남구  
2       12    220000   4  1987.0        언주로 3      NaN  중개거래          서울 강남구  
3       21    220000   2  1987.0        언주로 3      NaN  중개거래          서울 강남구  
4       27    216000   2  1987.0        언주로 3      NaN  중개거래          서울 강남구  
...    ...       ...  ..     ...          ...      ...   ...             ...  
16942   20     74000   3  1997.0      동일로 752      NaN  중개거래          서울 중랑구  
16943   27     91500  12  1997.0      동일로 752      NaN  중개거래          서울 중랑구  
16944    4     50000   2  2003.0   동일로144길 74      NaN  중개거래  서울 송파구, 서울 중랑구  
16945    9     49900   7  2003.0   동일로144길 74      NaN  중개거래          서울 중랑구  
16946   23     53000   6  2007.0  봉화산로27가길 19      NaN  중개거래          서울 중랑구  

[16947 rows x 15 columns]

In [132]:
apt_price.shape, apt_price.size

((16947, 15), 254205)

In [133]:
평 = apt_price['전용면적(㎡)']/3.03

In [134]:
apt_price['거래금액(만원)']/평

0        8335.625860
1        8146.179817
2        8335.625860
3        8335.625860
4        8184.069026
            ...     
16942    3752.008032
16943    3299.357372
16944    1788.877081
16945    1785.299327
16946    2101.138296
Length: 16947, dtype: float64

In [135]:
%whos

Variable    Type         Data/Info
----------------------------------
apt_price   DataFrame                     시군구     <...>[16947 rows x 15 columns]
arr1        ndarray      4: 4 elems, type `int32`, 16 bytes
arr2        ndarray      2x3: 6 elems, type `int32`, 24 bytes
arr3        ndarray      2x2x3: 12 elems, type `int32`, 48 bytes
arr4        ndarray      16: 16 elems, type `int32`, 64 bytes
my_list     list         n=4
my_list2    list         n=2
np          module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
pd          module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
평           Series       0        26.392739\n1    <...>th: 16947, dtype: float64


In [137]:
arr5 = np.arange(9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [143]:
arr5[1][1]
arr5[1,1]

4

In [138]:
arr6 = np.arange(9)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [139]:
arr6[1]

1

In [147]:
bidx = arr5 % 2 ==0
bidx

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [148]:
arr5[bidx] # True에 위치한 값을 추출, 1차원 반환

array([0, 2, 4, 6, 8])

In [150]:
arr5[arr5 % 2 == 0]

array([0, 2, 4, 6, 8])

In [154]:
apt_price[apt_price['층'] == 2]

시군구      번지      본번    부번             단지명  전용면적(㎡)    계약년월  \
0      서울특별시 강남구 개포동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202109   
3      서울특별시 강남구 개포동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
4      서울특별시 강남구 개포동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202205   
7      서울특별시 강남구 개포동    1282  1282.0   0.0       개포래미안포레스트    74.66  202109   
19     서울특별시 강남구 개포동    12-2    12.0   2.0      개포자이(12-2)   168.42  202202   
...              ...     ...     ...   ...             ...      ...     ...   
16900  서울특별시 중랑구 신내동     654   654.0   0.0           진로아파트   134.37  202205   
16901  서울특별시 중랑구 신내동     654   654.0   0.0           진로아파트   134.37  202206   
16907  서울특별시 중랑구 신내동     656   656.0   0.0        화성.두산아파트    66.96  202203   
16909  서울특별시 중랑구 신내동     656   656.0   0.0        화성.두산아파트    66.96  202205   
16944  서울특별시 중랑구 중화동  274-51   274.0  51.0         한영(101)    84.69  202111   

       계약일  거래금액(만원)  층    건축년도         도로명  해제사유발생일  거래유형          중개사소재지  
0        2    220000  2  1987.0       언주로 3      NaN     -               -  
3       21    220000  2  1987.0       언주로 3      NaN  중개거래          서울 강남구  
4       27    216000  2  1987.0       언주로 3      NaN  중개거래          서울 강남구  
7       16    253000  2  2020.0     개포로 264      NaN     -               -  
19       7    246000  2  2004.0  개포로109길 69      NaN  중개거래          서울 강남구  
...    ...       ... ..     ...         ...      ...   ...             ...  
16900   30    109000  2  1995.0   신내로17길 41      NaN  중개거래          서울 중랑구  
16901    8    110000  2  1995.0   신내로17길 41      NaN  중개거래          서울 중랑구  
16907   12     71000  2  1995.0     신내로 155      NaN  중개거래  서울 송파구, 서울 중랑구  
16909    9     69000  2  1995.0     신내로 155      NaN  중개거래  서울 송파구, 서울 중랑구  
16944    4     50000  2  2003.0  동일로144길 74      NaN  중개거래  서울 송파구, 서울 중랑구  

[1019 rows x 15 columns]

In [167]:
# 서울특별시 강동구 암사동 거래정보만 추출
bidx = apt_price['시군구'] == '서울특별시 강동구 암사동'
sum(bidx) # True -> 1, False -> 0

78

In [166]:
apt_price[bidx] #True에 위치하는 행들만 추출

시군구     번지     본번   부번           단지명   전용면적(㎡)    계약년월  계약일  \
1625  서울특별시 강동구 암사동  466-3  466.0  3.0         내일쎄닛빌  111.4000  202205   11   
1626  서울특별시 강동구 암사동    461  461.0  0.0            대원   59.9000  202201   17   
1627  서울특별시 강동구 암사동  501-4  501.0  4.0         동양넥스빌   84.6800  202205   10   
1628  서울특별시 강동구 암사동  414-2  414.0  2.0       롯데캐슬퍼스트   59.9900  202109    8   
1629  서울특별시 강동구 암사동  414-2  414.0  2.0       롯데캐슬퍼스트   59.9900  202109   11   
...             ...    ...    ...  ...           ...       ...     ...  ...   
1698  서울특별시 강동구 암사동    400  400.0  0.0         현대홈타운   84.9800  202204   20   
1699  서울특별시 강동구 암사동    400  400.0  0.0         현대홈타운  114.0700  202205   30   
1700  서울특별시 강동구 암사동    675  675.0  0.0  힐스테이트 강동 리버뷰   84.9979  202203   29   
1701  서울특별시 강동구 암사동    675  675.0  0.0  힐스테이트 강동 리버뷰   84.9921  202204    1   
1702  서울특별시 강동구 암사동    675  675.0  0.0  힐스테이트 강동 리버뷰   84.9628  202205    6   

      거래금액(만원)   층    건축년도         도로명  해제사유발생일  거래유형          중개사소재지  
1625     72000   9  2007.0  고덕로20나길 49      NaN   직거래               -  
1626     72500  12  1998.0      고덕로 52      NaN  중개거래  서울 강남구, 서울 강동구  
1627     80000  10  1999.0      상암로 41      NaN  중개거래          서울 강동구  
1628    129700  18  2008.0     고덕로 131      NaN     -               -  
1629    125500   3  2008.0     고덕로 131      NaN     -               -  
...        ...  ..     ...         ...      ...   ...             ...  
1698    137500  18  2004.0   고덕로27길 36      NaN  중개거래          서울 강동구  
1699    155000  11  2004.0   고덕로27길 36      NaN  중개거래          서울 강동구  
1700    130000   4  2019.0  올림픽로91길 30      NaN  중개거래          서울 강동구  
1701    164000  23  2019.0  올림픽로91길 30      NaN  중개거래          서울 강동구  
1702    152000   7  2019.0  올림픽로91길 30      NaN  중개거래        경기 성남분당구  

[78 rows x 15 columns]

In [172]:
arr5[0,2],arr5[1,1]

(2, 4)

In [175]:
arr5[ [0,1], [2,1]]

array([2, 4])

In [176]:
arr5[0,:]

array([0, 1, 2])

In [177]:
arr5[:,0]

array([0, 3, 6])

In [215]:
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [208]:
arr5[[0,2]
     [:2]]

array([[0, 1, 2],
       [6, 7, 8]])

In [214]:
b = arr5[:,1]
b

array([1, 4, 7])

In [216]:
b[0]=10
arr5

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [217]:
b = arr5[:,1].copy() # 복사본
b

array([10,  4,  7])

In [218]:
b[0] = 1
arr5

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [219]:
np.where(arr5 % 2 == 0)

(array([0, 0, 0, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 1, 0, 2], dtype=int64))

In [220]:
np.where(arr5 % 2 == 0,'짝수','홀수')

array([['짝수', '짝수', '짝수'],
       ['홀수', '짝수', '홀수'],
       ['짝수', '홀수', '짝수']], dtype='<U2')

In [224]:
# 조건에 맞는 항목은 "짝수", 아닐 경우 원래값 유지
np.where(arr5 % 2 == 0 ,'짝수',arr5)

array([['짝수', '짝수', '짝수'],
       ['3', '짝수', '5'],
       ['짝수', '7', '짝수']], dtype='<U11')

In [231]:
arr5.sum()

45

In [ ]:
arr5.sum(axis=0) # column 별 통계
arr5.sum(axis=1) # row 별 통계